[package]
name = "merge_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alphanumeric-sort = "1.4.0"
clap = { version = "4.4.12", features = ["derive"] }
chrono = "0.4"